House/Models/ErrorViewModel.cs
using System;

namespace House.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

House/Models/House/HouseListItem.cs
using System;

namespace House.Models.House
{
    public class HouseListItem
    {
        public Guid? Id { get; set; }
        public double TotalArea { get; set; }
        public string Address { get; set; }
        public string Details { get; set; }
        public int Price { get; set; }
        public int Rooms { get; set; }
        public int Year { get; set; }

    }
}

House/Models/House/HouseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace House.Models.House
{
    public class HouseViewModel
    {
        public Guid? Id { get; set; }
        public double TotalArea { get; set; }
        public string Address { get; set; }
        public string Details { get; set; }
        public int Price { get; set; }
        public int Rooms { get; set; }
        public int Year { get; set; }

    }
}

House/Controllers/HomeController.cs
using House.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace House.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

House/Controllers/HouseController.cs
using House.Core.Dtos;
using House.Core.ServiceInterface;
using House.Data;
using House.Models.House;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace House.Controllers
{
    public class HouseController : Controller
    {
        private readonly HouseDbContext _context;
        private readonly IHouseServices _houseService;

        public HouseController
            (
            HouseDbContext context,
            IHouseServices houseService
            )
        {
            _context = context;
            _houseService = houseService;
        }

        //ListItem
        [HttpGet]
        public IActionResult Index()
        {
            var result = _context.House
                .Select(x => new HouseListItem
                {
                    Id = x.Id,
                    TotalArea = x.TotalArea,
                    Address = x.Address,
                    Details = x.Details,
                    Price = x.Price,
                    Rooms = x.Rooms,
                    Year = x.Year
                });

            return View(result);
        }

        [HttpGet]
        public IActionResult Add()
        {
            HouseViewModel model = new HouseViewModel();

            return View("Edit", model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(HouseViewModel model)
        {
            var dto = new HouseDto()
            {
                Id = model.Id,
                TotalArea = model.TotalArea,
                Address = model.Address,
                Details = model.Details,
                Price = model.Price,
                Rooms = model.Rooms,
                Year = model.Year

            };

            var result = await _houseService.Add(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var house = await _houseService.Delete(id);
            if (house == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var house = await _houseService.GetAsync(id);

            if (house == null)
            {
                return NotFound();
            }

            var model = new HouseViewModel();

            model.Id = house.Id;
            model.TotalArea = house.TotalArea;
            model.Address = house.Address;
            model.Details = house.Details;
            model.Price = house.Price;
            model.Rooms = house.Rooms;
            model.Year = house.Year;

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(HouseViewModel model)
        {
            var dto = new HouseDto()
            {
                Id = model.Id,
                TotalArea = model.TotalArea,
                Address = model.Address,
                Details = model.Details,
                Price = model.Price,
                Rooms = model.Rooms,
                Year = model.Year
                
            };

            var result = await _houseService.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), model);
        }

    }
}

House/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

House/Views/House/Edit.cshtml
@model House.Models.House.HouseViewModel


@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Add</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />

        <div class="form-group row">
            <label asp-for="TotalArea" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="TotalArea" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Address" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Details" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <textarea asp-for="Details" class="form-control" rows="5"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Price" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Rooms" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Rooms" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Year" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Year" class="form-control" />
            </div>
        </div>

        @if (Model.Id.HasValue)
        {
            <input asp-action="edit" asp-controller="house" type="submit" class="btn btn-primary" value="Update">
            <input asp-action="delete" asp-controller="house" asp-for="Id" type="submit" class="btn btn-danger" value="Delete">
        }
        else
        {
            <input asp-action="add" asp-controller="house" type="submit" class="btn btn-primary" value="Add">
        }
        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileLabel = $(this).next('.custom-file-label');
                var files = $(this)[0].files;
                if (files.length > 1) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length == 1) {
                    fileLabel.html(files[0].name);
                }
                //$(this).next('.custom-file-label').html(fileLabel);
            });
        });
    </script>
}

House/Views/House/Index.cshtml
@model IEnumerable<House.Models.House.HouseListItem>

@{
    int queueNumber = 0;
}

<div class="h1">
    Houses
</div>

<div class="">
    <a asp-action="add" asp-controller="house" type="submit" class="btn btn-primary">Add</a>
</div>
<form method="post" class="m-1">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">TotalArea</th>
                <th scope="col">Address</th>
                <th scope="col">Details</th>
                <th scope="col">Price</th>
                <th scope="col">Rooms</th>
                <th scope="col">Year</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var house in Model)
            {
                queueNumber += 1;

            <tr>
                <th scope="row">@queueNumber</th>
                <td class="">@house.TotalArea</td>
                <td class="">@house.Address</td>
                <td class="">@house.Details</td>
                <td class="">@house.Price</td>
                <td class="">@house.Rooms</td>
                <td class="">@house.Year</td>
                <td class="">
                    <a asp-action="edit" asp-controller="house" asp-route-id="@house.Id" class="btn btn-primary">Edit</a>
                    <input asp-action="delete" asp-controller="house" asp-route-id="@house.Id" type="submit" class="btn btn-danger" value="Delete">
                </td>
            </tr>
            }
        </tbody>

    </table>
</form>

House/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - House</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">House</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Index">House</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - House - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>